import type { ProjectItem } from "./project-types";

export const MOCK_PROJECTS: ProjectItem[] = [
  {
    id: "building-seoul-station-north",
    category: "building",
    name: "서울역 북부역세권 복합개발",
    description: "오피스, 호텔, 컨벤션 시설이 결합된 대형 복합개발 사업입니다.",
    latitude: 37.5563,
    longitude: 126.9706,
    address: "서울 중구 봉래동2가 일대",
    status: "in_progress",
    sourceName: "서울시",
    sourceUrl: "https://news.seoul.go.kr/citybuild/",
    startDate: "2024-01",
    endDate: "2029-12",
    updatedAt: "2026-02-10",
  },
  {
    id: "building-yeouido-seoul-anchor",
    category: "building",
    name: "여의도 서울앵커원 신축",
    description: "업무시설 중심의 대형 신축 프로젝트입니다.",
    latitude: 37.5258,
    longitude: 126.9244,
    address: "서울 영등포구 여의도동",
    status: "in_progress",
    sourceName: "영등포구",
    sourceUrl: "https://www.ydp.go.kr/",
    startDate: "2023-11",
    endDate: "2027-06",
    updatedAt: "2026-01-22",
  },
  {
    id: "building-jamsil-mice",
    category: "building",
    name: "잠실 MICE 복합개발",
    description: "전시장, 업무, 숙박, 상업시설이 함께 들어서는 대형 사업입니다.",
    latitude: 37.5147,
    longitude: 127.1042,
    address: "서울 송파구 잠실동 일대",
    status: "approved",
    sourceName: "서울시",
    sourceUrl: "https://news.seoul.go.kr/economy/",
    startDate: "2026-01",
    endDate: "2031-12",
    updatedAt: "2026-02-05",
  },
  {
    id: "railway-gtx-a-suseo",
    category: "railway",
    name: "GTX-A 수서-동탄 구간 후속 공정",
    description: "수서권역 주변에서 체감되는 광역철도 공정 구간입니다.",
    latitude: 37.4875,
    longitude: 127.1013,
    address: "서울 강남구 수서동",
    status: "in_progress",
    sourceName: "국토교통부",
    sourceUrl: "https://www.molit.go.kr/",
    startDate: "2019-06",
    endDate: "2028-12",
    updatedAt: "2026-01-18",
  },
  {
    id: "railway-gtx-c-changdong",
    category: "railway",
    name: "GTX-C 창동권 공사",
    description: "창동역 일대에서 진행 중인 광역철도 사업입니다.",
    latitude: 37.6531,
    longitude: 127.0475,
    address: "서울 도봉구 창동",
    status: "in_progress",
    sourceName: "국가철도공단",
    sourceUrl: "https://www.kr.or.kr/",
    startDate: "2024-04",
    endDate: "2030-12",
    updatedAt: "2026-02-03",
  },
  {
    id: "railway-sinchon-line",
    category: "railway",
    name: "신안산선 여의도-신촌 연결 공정",
    description: "도심 구간 굴착과 펜스 공사가 이어지는 철도 사업입니다.",
    latitude: 37.5279,
    longitude: 126.9325,
    address: "서울 영등포구 여의도동 일대",
    status: "in_progress",
    sourceName: "넥스트레인",
    sourceUrl: "https://www.nexttrain.co.kr/",
    startDate: "2020-05",
    endDate: "2027-12",
    updatedAt: "2026-01-30",
  },
  {
    id: "housing-wangsuk",
    category: "housing",
    name: "남양주 왕숙 공공주택지구",
    description: "대규모 공공택지 조성 사업으로 기반시설 공사가 진행 중입니다.",
    latitude: 37.6391,
    longitude: 127.1818,
    address: "경기 남양주시 진접읍·진건읍 일대",
    status: "in_progress",
    sourceName: "LH",
    sourceUrl: "https://www.lh.or.kr/",
    startDate: "2023-09",
    endDate: "2032-12",
    updatedAt: "2026-02-07",
  },
  {
    id: "housing-gyeyang",
    category: "housing",
    name: "인천 계양 3기 신도시",
    description: "공공주택과 광역교통 대책이 함께 추진되는 택지개발지구입니다.",
    latitude: 37.5598,
    longitude: 126.7326,
    address: "인천 계양구 귤현동 일대",
    status: "in_progress",
    sourceName: "LH",
    sourceUrl: "https://www.lh.or.kr/",
    startDate: "2024-02",
    endDate: "2031-12",
    updatedAt: "2026-01-16",
  },
  {
    id: "housing-daejang",
    category: "housing",
    name: "부천 대장 공공주택지구",
    description: "대형 펜스와 기반시설 정비가 동반되는 공공택지 사업입니다.",
    latitude: 37.5278,
    longitude: 126.7946,
    address: "경기 부천시 대장동 일대",
    status: "approved",
    sourceName: "LH",
    sourceUrl: "https://www.lh.or.kr/",
    startDate: "2025-03",
    endDate: "2030-12",
    updatedAt: "2026-02-01",
  },
  {
    id: "building-suwon-mice",
    category: "building",
    name: "수원 R&D 사이언스파크 복합개발",
    description: "연구시설과 업무시설을 포함한 대형 신축 사업입니다.",
    latitude: 37.2864,
    longitude: 127.0227,
    address: "경기 수원시 권선구",
    status: "approved",
    sourceName: "수원시",
    sourceUrl: "https://www.suwon.go.kr/",
    startDate: "2025-08",
    endDate: "2030-06",
    updatedAt: "2026-01-12",
  },
  {
    id: "railway-incheon2-extension",
    category: "railway",
    name: "인천2호선 고양 연장 사업",
    description: "수도권 서북부 연결을 위한 철도 연장 사업입니다.",
    latitude: 37.6777,
    longitude: 126.7478,
    address: "경기 고양시 덕양구 일대",
    status: "approved",
    sourceName: "국토교통부",
    sourceUrl: "https://www.molit.go.kr/",
    startDate: "2025-10",
    endDate: "2031-12",
    updatedAt: "2026-02-11",
  },
  {
    id: "housing-goyang-changneung",
    category: "housing",
    name: "고양 창릉 공공주택지구",
    description: "대규모 도시개발지구 조성 사업으로 토목 공사가 이어지고 있습니다.",
    latitude: 37.6488,
    longitude: 126.8719,
    address: "경기 고양시 덕양구 창릉동 일대",
    status: "in_progress",
    sourceName: "LH",
    sourceUrl: "https://www.lh.or.kr/",
    startDate: "2024-06",
    endDate: "2032-12",
    updatedAt: "2026-02-08",
  },
];
