import type { ProjectItem } from "./project-types";

// Fallback snapshot of public-data-backed projects for offline/file-load failure.
export const MOCK_PROJECTS: ProjectItem[] = [
  {
    id: "pc-yeongdong-daero",
    category: "public_construction",
    name: "영동대로 지하공간 복합개발",
    geometryType: "point",
    latitude: 37.5112,
    longitude: 127.0591,
    address: "서울 강남구 삼성동 영동대로 일대",
    status: "in_progress",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "서울특별시",
    startDate: "2021-06",
    endDate: "2029-12",
    description: "영동대로 지하 복합환승센터와 공공공간을 조성하는 대형 지하개발 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-dongbuganseon-underground",
    category: "public_construction",
    name: "동부간선도로 지하화 민간투자사업",
    geometryType: "point",
    latitude: 37.6102,
    longitude: 127.0707,
    address: "서울 노원구 월계동-강남구 대치동 축",
    status: "in_progress",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "서울특별시",
    startDate: "2024-10",
    endDate: "2034-12",
    description: "상습 정체 구간 개선을 위한 지하화 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-olympic-gayang-haengju",
    category: "public_construction",
    name: "가양대교-행주대교 남단 올림픽대로 확장공사",
    geometryType: "point",
    latitude: 37.5698,
    longitude: 126.8393,
    address: "서울 강서구 방화동 일대",
    status: "in_progress",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "서울특별시",
    startDate: "2023-04",
    endDate: "2027-12",
    description: "올림픽대로 병목 완화를 위한 확장 공사.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-seoul-sejong-expressway",
    category: "public_construction",
    name: "서울-세종고속도로 안성-구리 건설사업",
    geometryType: "point",
    latitude: 37.5944,
    longitude: 127.1901,
    address: "경기 구리시 토평동 일대",
    status: "in_progress",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "한국도로공사",
    startDate: "2019-12",
    endDate: "2027-12",
    description: "수도권 동남부 교통 분산을 위한 고속도로 건설 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-ring2-paju-yangju",
    category: "public_construction",
    name: "수도권제2순환고속도로 파주-양주 건설사업",
    geometryType: "point",
    latitude: 37.7811,
    longitude: 126.8765,
    address: "경기 파주시 산남동 일대",
    status: "in_progress",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "한국도로공사",
    startDate: "2021-01",
    endDate: "2026-12",
    description: "수도권 외곽 순환축 연결을 위한 고속도로 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-ring2-pocheon-hwado",
    category: "public_construction",
    name: "수도권제2순환고속도로 포천-화도 건설사업",
    geometryType: "point",
    latitude: 37.7448,
    longitude: 127.3112,
    address: "경기 남양주시 화도읍 일대",
    status: "in_progress",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "한국도로공사",
    startDate: "2021-12",
    endDate: "2026-12",
    description: "수도권 동북부 순환축을 잇는 고속도로 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-ring2-ansan-incheon",
    category: "public_construction",
    name: "수도권제2순환고속도로 안산-인천 건설사업",
    geometryType: "point",
    latitude: 37.3573,
    longitude: 126.7284,
    address: "경기 안산시 단원구 성곡동 일대",
    status: "in_progress",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "한국도로공사",
    startDate: "2021-03",
    endDate: "2029-12",
    description: "인천항과 서남권 산업벨트를 연결하는 순환축 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-incheon-airport-phase4",
    category: "public_construction",
    name: "인천국제공항 4단계 건설사업",
    geometryType: "point",
    latitude: 37.4602,
    longitude: 126.4407,
    address: "인천 중구 운서동 인천국제공항 일대",
    status: "in_progress",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "인천국제공항공사",
    startDate: "2019-11",
    endDate: "2030-12",
    description: "여객·화물 수용능력 확대를 위한 공항 확장 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-yeongjong-sindo",
    category: "public_construction",
    name: "영종-신도 평화도로 건설공사",
    geometryType: "point",
    latitude: 37.5328,
    longitude: 126.4939,
    address: "인천 중구 북도면 신도리 일대",
    status: "in_progress",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "인천광역시",
    startDate: "2021-12",
    endDate: "2026-12",
    description: "영종과 신도를 연결하는 연륙교 건설 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-seoul-arena",
    category: "public_construction",
    name: "서울아레나 복합문화시설 건립사업",
    geometryType: "point",
    latitude: 37.6532,
    longitude: 127.0479,
    address: "서울 도봉구 창동 일대",
    status: "in_progress",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "서울특별시",
    startDate: "2024-07",
    endDate: "2027-12",
    description: "창동 신경제중심지 조성을 위한 대형 공연장 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-changdong-kpop-arena",
    category: "public_construction",
    name: "창동 K-POP 아레나 건립사업",
    geometryType: "point",
    latitude: 37.6547,
    longitude: 127.0507,
    address: "서울 도봉구 창동 서울아레나 인근",
    status: "approved",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "서울특별시",
    startDate: "2026-01",
    endDate: "2029-12",
    description: "창동 일대 문화산업 거점 조성을 위한 공연 인프라 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-seoul-station-north-infra",
    category: "public_construction",
    name: "서울역 북부역세권 기반시설 조성공사",
    geometryType: "point",
    latitude: 37.5564,
    longitude: 126.9691,
    address: "서울 중구 봉래동2가 서울역 북부 일대",
    status: "in_progress",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "서울특별시",
    startDate: "2024-01",
    endDate: "2029-12",
    description: "북부역세권 복합개발과 연계된 공공기반시설 공사.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-jamsil-mice-infra",
    category: "public_construction",
    name: "잠실 스포츠·MICE 복합개발 기반시설 공사",
    geometryType: "point",
    latitude: 37.515,
    longitude: 127.1039,
    address: "서울 송파구 잠실동 종합운동장 일대",
    status: "approved",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "서울특별시",
    startDate: "2026-01",
    endDate: "2031-12",
    description: "잠실 MICE 사업과 연동되는 공공기반시설 조성 공사.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-yongsan-ibd-infra",
    category: "public_construction",
    name: "용산국제업무지구 기반시설 조성사업",
    geometryType: "point",
    latitude: 37.5292,
    longitude: 126.9552,
    address: "서울 용산구 한강로3가 일대",
    status: "approved",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "서울특별시",
    startDate: "2025-09",
    endDate: "2035-12",
    description: "용산 국제업무지구 조성을 위한 선행 기반시설 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-suwon-rnd",
    category: "public_construction",
    name: "수원 R&D 사이언스파크 조성사업",
    geometryType: "point",
    latitude: 37.2864,
    longitude: 127.0227,
    address: "경기 수원시 권선구 입북동 일대",
    status: "approved",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "수원특례시",
    startDate: "2025-08",
    endDate: "2030-06",
    description: "연구개발 중심 복합단지 조성 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-gwangmyeong-siheung-tech",
    category: "public_construction",
    name: "광명시흥 도시첨단산업단지 기반시설 조성사업",
    geometryType: "point",
    latitude: 37.4528,
    longitude: 126.8468,
    address: "경기 광명시 가학동-시흥시 과림동 일대",
    status: "in_progress",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "경기도",
    startDate: "2024-03",
    endDate: "2030-12",
    description: "산업·주거 복합 개발을 위한 기반시설 정비 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-gwacheon-info-infra",
    category: "public_construction",
    name: "과천지식정보타운 공공기반시설 조성사업",
    geometryType: "point",
    latitude: 37.4218,
    longitude: 126.9992,
    address: "경기 과천시 갈현동 일대",
    status: "in_progress",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "과천시",
    startDate: "2023-01",
    endDate: "2027-12",
    description: "지식정보타운 입주와 연계된 도로·공원 등 기반시설 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-seongsa-innovation",
    category: "public_construction",
    name: "고양 성사혁신지구 공공개발사업",
    geometryType: "point",
    latitude: 37.6587,
    longitude: 126.8326,
    address: "경기 고양시 덕양구 성사동 일대",
    status: "in_progress",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "고양특례시",
    startDate: "2023-05",
    endDate: "2028-12",
    description: "원당역세권 복합개발을 위한 공공개발 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-magog-mice",
    category: "public_construction",
    name: "마곡 MICE 복합개발 기반시설 조성",
    geometryType: "point",
    latitude: 37.5639,
    longitude: 126.8257,
    address: "서울 강서구 마곡동 일대",
    status: "approved",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "서울특별시",
    startDate: "2025-12",
    endDate: "2031-12",
    description: "마곡 일대 전시·업무 복합단지 조성을 위한 기반시설 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-yeouido-finance",
    category: "public_construction",
    name: "여의도 금융중심지 일대 기반시설 정비사업",
    geometryType: "point",
    latitude: 37.5229,
    longitude: 126.9242,
    address: "서울 영등포구 여의도동 일대",
    status: "planned",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "서울특별시",
    startDate: "2026-06",
    endDate: "2032-12",
    description: "여의도 재정비와 연계된 공공기반시설 정비 계획.",
    updatedAt: "2026-03-09",
  },
  {
    id: "pc-gimpo-hangang2-infra",
    category: "public_construction",
    name: "김포한강2 공공주택지구 기반시설 조성공사",
    geometryType: "point",
    latitude: 37.6452,
    longitude: 126.6725,
    address: "경기 김포시 마산동-운양동 일대",
    status: "approved",
    sourceName: "국토교통부 공공건설 공사위치정보",
    sourceUrl: "https://www.data.go.kr/data/15094259/fileData.do",
    agency: "LH",
    startDate: "2025-11",
    endDate: "2032-12",
    description: "김포한강2 지구 조성을 위한 선행 기반시설 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "rail-gtx-a",
    category: "railway",
    name: "GTX-A 노선 건설사업",
    geometryType: "point",
    latitude: 37.4875,
    longitude: 127.1013,
    address: "서울 강남구 수서동 일대",
    status: "in_progress",
    sourceName: "국가철도공단 철도공단사업",
    sourceUrl: "https://www.data.go.kr/data/15088605/fileData.do",
    agency: "국가철도공단",
    startDate: "2019-06",
    endDate: "2028-12",
    description: "수도권 광역급행철도 A노선 잔여 구간 및 후속 공정 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "rail-gtx-b",
    category: "railway",
    name: "GTX-B 노선 민자사업",
    geometryType: "point",
    latitude: 37.3943,
    longitude: 126.6368,
    address: "인천 연수구 송도동 일대",
    status: "approved",
    sourceName: "국가철도공단 철도공단사업",
    sourceUrl: "https://www.data.go.kr/data/15088605/fileData.do",
    agency: "국가철도공단",
    startDate: "2025-03",
    endDate: "2030-12",
    description: "송도-서울-남양주를 잇는 광역급행철도 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "rail-gtx-c",
    category: "railway",
    name: "GTX-C 노선 민자사업",
    geometryType: "point",
    latitude: 37.6531,
    longitude: 127.0475,
    address: "서울 도봉구 창동역 일대",
    status: "approved",
    sourceName: "국가철도공단 철도공단사업",
    sourceUrl: "https://www.data.go.kr/data/15088605/fileData.do",
    agency: "국가철도공단",
    startDate: "2025-01",
    endDate: "2030-12",
    description: "양주-수원 구간 광역급행철도 건설 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "rail-sinansan",
    category: "railway",
    name: "신안산선 복선전철 민간투자사업",
    geometryType: "point",
    latitude: 37.5262,
    longitude: 126.9136,
    address: "서울 영등포구 여의도동 일대",
    status: "in_progress",
    sourceName: "국가철도공단 철도공단사업",
    sourceUrl: "https://www.data.go.kr/data/15088605/fileData.do",
    agency: "국가철도공단",
    startDate: "2019-09",
    endDate: "2027-12",
    description: "안산·시흥과 서울 여의도를 연결하는 광역철도 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "rail-wolgot-pangyo",
    category: "railway",
    name: "월곶-판교 복선전철 건설사업",
    geometryType: "point",
    latitude: 37.3919,
    longitude: 126.7861,
    address: "경기 시흥시 월곶동 일대",
    status: "in_progress",
    sourceName: "국가철도공단 철도공단사업",
    sourceUrl: "https://www.data.go.kr/data/15088605/fileData.do",
    agency: "국가철도공단",
    startDate: "2024-01",
    endDate: "2030-12",
    description: "시흥-성남을 잇는 수도권 동서축 철도 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "rail-indeokwon-dongtan",
    category: "railway",
    name: "인덕원-동탄 복선전철 건설사업",
    geometryType: "point",
    latitude: 37.4019,
    longitude: 126.9802,
    address: "경기 안양시 동안구 관양동 인덕원역 일대",
    status: "in_progress",
    sourceName: "국가철도공단 철도공단사업",
    sourceUrl: "https://www.data.go.kr/data/15088605/fileData.do",
    agency: "국가철도공단",
    startDate: "2024-12",
    endDate: "2031-12",
    description: "안양-수원-화성을 연결하는 복선전철 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "rail-dobongsan-okjeong",
    category: "railway",
    name: "도봉산-옥정 광역철도 건설사업",
    geometryType: "point",
    latitude: 37.7044,
    longitude: 127.0452,
    address: "경기 양주시 옥정동 일대",
    status: "in_progress",
    sourceName: "국가철도공단 철도공단사업",
    sourceUrl: "https://www.data.go.kr/data/15088605/fileData.do",
    agency: "국가철도공단",
    startDate: "2024-07",
    endDate: "2029-12",
    description: "양주 옥정과 서울 도봉산을 잇는 광역철도 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "housing-wangsuk",
    category: "housing",
    name: "남양주 왕숙 공공주택지구",
    geometryType: "point",
    latitude: 37.6404,
    longitude: 127.1832,
    address: "경기 남양주시 진접읍·진건읍 일대",
    status: "in_progress",
    sourceName: "국토교통부 택지정보 단계별사업정보",
    sourceUrl: "https://www.data.go.kr/data/15149148/fileData.do",
    agency: "LH",
    startDate: "2023-09",
    endDate: "2032-12",
    description: "3기 신도시 왕숙지구 조성 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "housing-wangsuk2",
    category: "housing",
    name: "남양주 왕숙2 공공주택지구",
    geometryType: "point",
    latitude: 37.6069,
    longitude: 127.1615,
    address: "경기 남양주시 일패동·이패동 일대",
    status: "approved",
    sourceName: "국토교통부 택지정보 단계별사업정보",
    sourceUrl: "https://www.data.go.kr/data/15149148/fileData.do",
    agency: "LH",
    startDate: "2025-01",
    endDate: "2033-12",
    description: "왕숙 권역 주택공급 확대를 위한 공공주택지구 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "housing-gyosan",
    category: "housing",
    name: "하남 교산 공공주택지구",
    geometryType: "point",
    latitude: 37.5356,
    longitude: 127.2141,
    address: "경기 하남시 천현동·교산동 일대",
    status: "in_progress",
    sourceName: "국토교통부 택지정보 단계별사업정보",
    sourceUrl: "https://www.data.go.kr/data/15149148/fileData.do",
    agency: "LH",
    startDate: "2024-02",
    endDate: "2032-12",
    description: "하남시 동부권 공공주택 공급을 위한 지구 조성 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "housing-changneung",
    category: "housing",
    name: "고양 창릉 공공주택지구",
    geometryType: "point",
    latitude: 37.6491,
    longitude: 126.8714,
    address: "경기 고양시 덕양구 창릉동 일대",
    status: "in_progress",
    sourceName: "국토교통부 택지정보 단계별사업정보",
    sourceUrl: "https://www.data.go.kr/data/15149148/fileData.do",
    agency: "LH",
    startDate: "2024-06",
    endDate: "2032-12",
    description: "고양시 서남권 대규모 공공주택지구 조성 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "housing-daejang",
    category: "housing",
    name: "부천 대장 공공주택지구",
    geometryType: "point",
    latitude: 37.5278,
    longitude: 126.7946,
    address: "경기 부천시 대장동 일대",
    status: "approved",
    sourceName: "국토교통부 택지정보 단계별사업정보",
    sourceUrl: "https://www.data.go.kr/data/15149148/fileData.do",
    agency: "LH",
    startDate: "2025-03",
    endDate: "2030-12",
    description: "서부권 주택공급 확대를 위한 공공주택지구 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "housing-gyeyang",
    category: "housing",
    name: "인천 계양 공공주택지구",
    geometryType: "point",
    latitude: 37.5598,
    longitude: 126.7326,
    address: "인천 계양구 귤현동 일대",
    status: "in_progress",
    sourceName: "국토교통부 택지정보 단계별사업정보",
    sourceUrl: "https://www.data.go.kr/data/15149148/fileData.do",
    agency: "LH",
    startDate: "2024-02",
    endDate: "2031-12",
    description: "인천 북부권 3기 신도시 조성 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "housing-gwacheon",
    category: "housing",
    name: "과천 과천 공공주택지구",
    geometryType: "point",
    latitude: 37.4386,
    longitude: 127.0108,
    address: "경기 과천시 주암동·과천동 일대",
    status: "approved",
    sourceName: "국토교통부 택지정보 단계별사업정보",
    sourceUrl: "https://www.data.go.kr/data/15149148/fileData.do",
    agency: "LH",
    startDate: "2025-05",
    endDate: "2032-12",
    description: "과천권 주택공급 확대를 위한 공공주택지구 사업.",
    updatedAt: "2026-03-09",
  },
  {
    id: "urban-seoul-station-plan",
    category: "urban_plan",
    name: "서울역 북부역세권 개발 실시계획",
    geometryType: "point",
    latitude: 37.5562,
    longitude: 126.9696,
    address: "서울 중구 봉래동2가 서울역 북부",
    status: "approved",
    sourceName: "국토교통부 (도시계획) 실시계획인가정보(월간)",
    sourceUrl: "https://www.data.go.kr/data/15047837/fileData.do",
    agency: "서울특별시",
    startDate: "2024-01",
    endDate: "2029-12",
    description: "서울역 북부역세권 복합개발 관련 도시계획 실시계획.",
    updatedAt: "2026-03-09",
  },
  {
    id: "urban-jamsil-plan",
    category: "urban_plan",
    name: "잠실 종합운동장 일대 도시계획시설 실시계획",
    geometryType: "point",
    latitude: 37.5158,
    longitude: 127.0728,
    address: "서울 송파구 잠실동 종합운동장 일대",
    status: "approved",
    sourceName: "국토교통부 (도시계획) 실시계획인가정보(월간)",
    sourceUrl: "https://www.data.go.kr/data/15047837/fileData.do",
    agency: "서울특별시",
    startDate: "2025-12",
    endDate: "2031-12",
    description: "잠실 스포츠·MICE 일대 도시계획시설 정비 실시계획.",
    updatedAt: "2026-03-09",
  },
  {
    id: "urban-yongsan-plan",
    category: "urban_plan",
    name: "용산국제업무지구 도시개발 실시계획",
    geometryType: "point",
    latitude: 37.5284,
    longitude: 126.9584,
    address: "서울 용산구 한강로3가 정비창 부지 일대",
    status: "approved",
    sourceName: "국토교통부 (도시계획) 실시계획인가정보(월간)",
    sourceUrl: "https://www.data.go.kr/data/15047837/fileData.do",
    agency: "서울특별시",
    startDate: "2025-09",
    endDate: "2035-12",
    description: "용산 정비창 부지 국제업무지구 개발 관련 실시계획.",
    updatedAt: "2026-03-09",
  },
  {
    id: "road-gyeongbu-anseong",
    category: "road",
    name: "경부고속도로 안성분기점 인근 시설개량 공사",
    geometryType: "point",
    latitude: 37.0658,
    longitude: 127.1584,
    address: "경기 안성시 원곡면 안성분기점 인근",
    status: "traffic_control",
    sourceName: "한국도로공사 공사 및 도로 차단 계획",
    sourceUrl: "https://www.data.go.kr/data/15076650/openapi.do",
    agency: "한국도로공사",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    description: "시설 개량 및 포장 보수를 위한 차단 계획 포함 공사.",
    updatedAt: "2026-03-09",
  },
  {
    id: "road-ring1-pangyo",
    category: "road",
    name: "수도권제1순환고속도로 판교분기점 인근 차단 계획",
    geometryType: "point",
    latitude: 37.3936,
    longitude: 127.0997,
    address: "경기 성남시 분당구 삼평동 판교분기점 인근",
    status: "traffic_control",
    sourceName: "한국도로공사 공사 및 도로 차단 계획",
    sourceUrl: "https://www.data.go.kr/data/15076650/openapi.do",
    agency: "한국도로공사",
    startDate: "2026-03-05",
    endDate: "2026-05-31",
    description: "분기점 안전시설 정비에 따른 차단 계획.",
    updatedAt: "2026-03-09",
  },
  {
    id: "road-yeongdong-gunja",
    category: "road",
    name: "영동고속도로 군자분기점 인근 포장보수 공사",
    geometryType: "point",
    latitude: 37.351,
    longitude: 126.7368,
    address: "경기 시흥시 정왕동 군자분기점 인근",
    status: "traffic_control",
    sourceName: "한국도로공사 공사 및 도로 차단 계획",
    sourceUrl: "https://www.data.go.kr/data/15076650/openapi.do",
    agency: "한국도로공사",
    startDate: "2026-03-02",
    endDate: "2026-04-30",
    description: "포장 보수와 안전시설 정비를 위한 공사 계획.",
    updatedAt: "2026-03-09",
  },
  {
    id: "road-seohaean-seopyeongtaek",
    category: "road",
    name: "서해안고속도로 서평택분기점 인근 차단 계획",
    geometryType: "point",
    latitude: 36.9895,
    longitude: 126.9347,
    address: "경기 평택시 포승읍 서평택분기점 인근",
    status: "traffic_control",
    sourceName: "한국도로공사 공사 및 도로 차단 계획",
    sourceUrl: "https://www.data.go.kr/data/15076650/openapi.do",
    agency: "한국도로공사",
    startDate: "2026-03-04",
    endDate: "2026-05-15",
    description: "시설 보수와 차로 운영 조정을 위한 차단 계획.",
    updatedAt: "2026-03-09",
  }
];
