name = "whatsinhere"
pages_build_output_dir = "dist"
compatibility_date = "2025-03-01"

[[d1_databases]]
binding = "DB"
database_name = "whatinhere-db"
database_id = "91d5aca5-84c5-46e3-9290-341952348b9b"

[vars]
VITE_KAKAO_MAP_JS_KEY = "196acd86c9ca7b2a46f77dd0d90f11f1"
