export const SAMPLE_PROJECTS = [
  {
    id: "kintex-hall-3",
    name: "킨텍스 제3전시장 건립",
    location: "경기 고양시 일산서구 킨텍스로 217-60 인근",
    status: "공사중",
    completionDate: "2028-12-31",
    description: "킨텍스 전시장 확충을 위한 대형 전시장 건립 사업.",
    link: "https://www.kintex.com/web/ko/html/company/exhibitionHall3.do",
    lat: 37.6679,
    lng: 126.7454,
  },
  {
    id: "goyang-cj-road",
    name: "고양시 광역도로 개선",
    location: "경기 고양시 일산동구 장항동 일대",
    status: "예정",
    completionDate: "2027-06-30",
    description: "교통 정체 완화를 위한 차로 확장 및 교차로 개선 계획.",
    link: "https://www.goyang.go.kr",
    lat: 37.6618,
    lng: 126.7672,
  },
  {
    id: "daehwa-station-area",
    name: "대화역 일대 복합개발",
    location: "경기 고양시 일산서구 대화동",
    status: "계획",
    completionDate: "2029-03-31",
    description: "역세권 상업·업무·주거 기능을 결합한 복합 개발 검토 사업.",
    link: "https://www.goyang.go.kr",
    lat: 37.6762,
    lng: 126.7475,
  },
  {
    id: "jangan-park-renewal",
    name: "장항지구 공원 재정비",
    location: "경기 고양시 일산동구 장항동",
    status: "공사중",
    completionDate: "2026-11-30",
    description: "보행 동선 개선 및 생활 SOC 확충을 포함한 공원 재정비 사업.",
    link: "https://www.goyang.go.kr",
    lat: 37.6589,
    lng: 126.7688,
  },
  {
    id: "ilsan-urban-plan",
    name: "일산 서부권 도시계획 변경",
    location: "경기 고양시 일산서구 일대",
    status: "계획",
    completionDate: "2027-12-31",
    description: "용도지역 조정 및 생활 인프라 확충을 위한 도시관리계획 변경.",
    link: "",
    lat: 37.6728,
    lng: 126.7311,
  },
];
